'use strict';
// tests for message_to_sqs
// Generated by serverless-mocha-plugin

const mod         = require('../twilio/message_to_sqs/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

describe('message_to_sqs', () => {
  before(function (done) {
    wrapper.init(mod);

    done()
  })
  
  it('implement tests here', (done) => {
    wrapper.init(mod);
    wrapper.run({reqbody:"a=1&b=12&c=13"}, (err, response) => {
      done('no tests implemented');
    });
  });
});
